# Generated by Django 4.2.2 on 2023-06-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='document',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
