# Generated by Django 4.1.9 on 2023-06-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorapp", "0002_remove_message_document_delete_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("content", models.TextField()),
                ("version", models.IntegerField(default=1)),
            ],
            options={
                "ordering": ("version",),
            },
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
